quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:quarkus_minimal;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=

muyun.database.primary-key-name=id
muyun.database.primary-key-type=STRING
muyun.database.default-schema=PUBLIC
muyun.database.repository-schema-mode=ENSURE
muyun.database.migration-mode=APPLY
muyun.database.install-common-plugins=true
muyun.database.install-postgres-plugins=false
