muyun.database.primary-key-name=id
muyun.database.primary-key-type=STRING
muyun.database.default-schema=public
muyun.database.migration-mode=APPLY
muyun.database.repository-schema-mode=ENSURE
quarkus.datasource.devservices.enabled=false
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:muyun_quarkus_it;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=sa
